### ISSUE TITLE
Levels and Experience are lost after game reset

### ISSUE THREAD

**Issue by RagguBaggu** [Arrenton/Shipwright#3]
As the title says, you can save and then reset the game using ctrl + r, and upon reloading the file your level returns to 1 and experience will be 0.

**Comment by P3rf3ctXZer0** [comment]
This is not an issue in at least version https://github.com/Arrenton/Shipwright/tree/7.1.0-leveled

![Discord_2zycKX5Ssm 1](https://github.com/Arrenton/Shipwright/assets/10351221/04f6765a-d69d-480e-b122-70709229d111) 

Been playing for 2 days

**Comment by Arrenton** [comment]
This was fixed some time ago, just forgot to close the issue.
